### PR TITLE
Fix HMR and integrate with node server

### LINKED ISSUE #47: Fix HMR and integrate with node server

### PR DESCRIPTION
**Pull request by tylerarbus**
Close #47 
Will finally make hot reloading work as expected! To launch the dev server type "npm run dev" - this will launch the node server on port 3000. Changes to any client files will automatically refresh on the screen, however server-side changes will still require a refresh.

If you're interested in hot reloading on the server side, check out this example: 
https://github.com/glenjamin/ultimate-hot-reloading-example

### CODE REVIEW

File: server/server.js [hunk 1]
```diff
@@ -5,6 +5,24 @@ const path = require('path');
 
 const app = express();
 
+if (process.env.NODE_ENV !== 'production') {
```
Comment (terencetmac) [inline server/server.js]: Should we extract this into a development module that we just require as a line in the beginning?

File: package.json [hunk 2]
```diff
@@ -9,8 +9,8 @@
   },
   "scripts": {
     "test": "jest",
-    "client-dev": "webpack-dev-server",
-    "server-dev": "nodemon server/server.js",
+    "build": "webpack --config ./webpack.config.js",
+    "dev": "npm build && nodemon server.js --ignore /client",
```
Comment (terencetmac) [inline package.json]: nodemon server/server.js instead please!
